### ISSUE TITLE
NPCLib following seems to be broken out of the box.

### ISSUE THREAD

**Issue by glen-mills** [ThePix/quest#11]
I've been trying to debug this, and will continue to do so, but thus far I am unsuccessful. 

Here is what currently happens in a fresh Quest game with just the Library: 
You tell an NPC to follow you.
You move.
The NPC does not follow.
Error running script: Object reference not set to an instance of an object.

NPC.following still shows as "player" as it should.
The follow message and wait message are displayed as intended.
The npc still prints the correct message when asking to follow if they are already following.

I'm trying to figure out where the bad reference is, but so far I can't locate it. I would greatly appreciate insight into this. For the time being I'll keep digging.

**Comment by ThePix** [comment]
Should now be fixed. Let me know if you find anything else.
