### ISSUE TITLE
Money in CombatLib

### ISSUE THREAD

**Issue by AtokradGames** [ThePix/quest#14]
I am working on a game set in modern times and would like to change the currency to dollars instead of gold coins, anyway I can do that?

**Comment by ThePix** [comment]
It can definitely be done. It is a long time since I did this, but I am pretty sure it just uses the standard Quest system, which is explained here:
http://docs.textadventures.co.uk/quest/functions/string/displaymoney.html

**Comment by AtokradGames** [comment]
Ok so I found a way to make my money work, I just created a new attribute instead of using quests default, but is there a way to make player health work, I don't seem to lose any when fighting.

**Comment by ThePix** [comment]
CombatLib uses the attribute "hitpoints", while Quest uses "health", which is always out of 100.

The best way to handle this would be to set "hitpoints" on the player to be a status attribute, and disable "health" (so basically what you are doing with money).

**Comment by AtokradGames** [comment]
Ok thank you!
