### ISSUE TITLE
Trouble trying to add verb synonyms for 'equip'

### ISSUE THREAD

**Issue by Himesjb** [ThePix/quest#5]
(Forgive me, I'm a beginner!).  I have tried to add synonyms for the verb "equip," by doing this:
![image](https://user-images.githubusercontent.com/43317915/45936163-fd36ae00-bf78-11e8-929b-ef9c332e080f.png)

It works, but when I play the game, the first thing shown is this:
Error running script: Error adding key 'equip' to dictionary: An item with the same key has already been added.

**Comment by Himesjb** [comment]
Never mind!  I figured out how to edit the Commands.xml file to do it...

**Comment by ThePix** [comment]
I have just uploaded a new version with the verbs names, so in future they can be over-ridden.
