### ISSUE TITLE
Issue with Conversations

### ISSUE THREAD

**Issue by TheSpyrexian** [ThePix/quest#8]
I follow the first paragraph of the guide for conversation, and create two topics, labelled correctly and under the name of the object who is set to character. I type in my conversation text. When I run the game, I click the menu and choose what I want to say, but all I get is - Error running script: Function not found: 'P.
I have attached a link to an unlisted YouTube video I uploaded to better show my issue.

--- https://youtu.be/6PElVI_8-U8 ---

Thanks for helping me :). I'm sure it's just something small that I've messed up.

**Comment by ThePix** [comment]
What version of Quest are you using? You will need Quest 5.7 or 5.8.

**Comment by TheSpyrexian** [comment]
I might have been using 5.6. I think it showed it in the video. Either way
I installed quest on a different PC and the library’s working fine now.
Thanks anyway :)

**Comment by ThePix** [comment]
I am going to close this then.
